"""fix foreign keys for room and board element

Revision ID: fff5505e6af2
Revises: 44ad9b413063
Create Date: 2026-04-07 00:10:35.887884

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = 'fff5505e6af2'
down_revision = '0a5b9ea5a834'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'board_element', 'room', ['room_id'], ['id'])
    op.create_foreign_key(None, 'board_element', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'room', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'room', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_constraint(None, 'board_element', type_='foreignkey')
    op.drop_constraint(None, 'board_element', type_='foreignkey')
    # ### end Alembic commands ###
