"""fix foreign keys for relations

Revision ID: 0cbe64b17e41
Revises: fff5505e6af2
Create Date: 2026-04-07 00:21:25.566982

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = '0cbe64b17e41'
down_revision = 'fff5505e6af2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, 'board_element_comment', 'board_element', ['board_element_id'], ['id']
    )
    op.create_foreign_key(None, 'board_element_comment', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'chat_message', 'user', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'chat_message', 'room', ['room_id'], ['id'])
    op.create_foreign_key(None, 'pomodoro_session', 'room', ['room_id'], ['id'])
    op.create_foreign_key(None, 'project', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'project_tag', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'project_tag', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'room_participant', 'room', ['room_id'], ['id'])
    op.create_foreign_key(None, 'room_participant', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_participant', type_='foreignkey')
    op.drop_constraint(None, 'room_participant', type_='foreignkey')
    op.drop_constraint(None, 'project_tag', type_='foreignkey')
    op.drop_constraint(None, 'project_tag', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'pomodoro_session', type_='foreignkey')
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_constraint(None, 'board_element_comment', type_='foreignkey')
    op.drop_constraint(None, 'board_element_comment', type_='foreignkey')
    # ### end Alembic commands ###
