"""add email notification table

Revision ID: 3e8ba93ed850
Revises: 9185abb29eef
Create Date: 2026-04-23 16:45:19.911129

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e8ba93ed850'
down_revision = '9185abb29eef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'email_notification',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('code', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column(
            'action',
            sa.Enum('VERIFY_ACCOUNT', 'CHANGE_PASSWORD', name='emailaction'),
            nullable=False,
        ),
        sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('is_used', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_email_notification_code'), 'email_notification', ['code'], unique=True
    )
    op.create_index(
        op.f('ix_email_notification_user_id'),
        'email_notification',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_email_notification_user_id'), table_name='email_notification'
    )
    op.drop_index(op.f('ix_email_notification_code'), table_name='email_notification')
    op.drop_table('email_notification')
    # ### end Alembic commands ###
