"""update pomodoro(created_at == send_at) session model

Revision ID: 7fa7989f06af
Revises: ec0db1362d90
Create Date: 2026-03-27 18:56:55.793338

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fa7989f06af'
down_revision = 'ec0db1362d90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'sent_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'chat_message',
        sa.Column(
            'sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
