"""init

Revision ID: 8c0033a7f747
Revises: fc0bae9e1153
Create Date: 2026-03-17 18:01:41.552671

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '8c0033a7f747'
down_revision: Union[str, Sequence[str], None] = 'fc0bae9e1153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
