"""fix model constraints and timezone fields

Revision ID: 9185abb29eef
Revises: 14e8881d5905
Create Date: 2026-04-18 20:41:40.816757

"""

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9185abb29eef'
down_revision = '14e8881d5905'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'pomodoro_session',
        'phase_ends_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        'pomodoro_session',
        'session_ends_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        'room',
        'ended_at',
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.create_unique_constraint('uq_tag_name', 'tag', ['name'])
    op.create_unique_constraint('uq_user_email', 'user', ['email'])
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_username', 'user', type_='unique')
    op.drop_constraint('uq_user_email', 'user', type_='unique')
    op.drop_constraint('uq_tag_name', 'tag', type_='unique')
    op.alter_column(
        'room',
        'ended_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        'pomodoro_session',
        'session_ends_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        'pomodoro_session',
        'phase_ends_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
