"""init

Revision ID: c2716a413fc3
Revises: f8c83c8104aa
Create Date: 2026-03-17 17:48:59.471972

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c2716a413fc3'
down_revision: Union[str, Sequence[str], None] = 'f8c83c8104aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
