"""init

Revision ID: cf12f7faa765
Revises: c2716a413fc3
Create Date: 2026-03-17 17:51:09.862697

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf12f7faa765'
down_revision: Union[str, Sequence[str], None] = 'c2716a413fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'project_tag',
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['project.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tag_id'],
            ['tag.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'board_element',
        sa.Column('element_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.Uuid(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['room_id'],
            ['room.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'chat_message',
        sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_edited', sa.Boolean(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.Uuid(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['room_id'],
            ['room.id'],
        ),
        sa.ForeignKeyConstraint(
            ['sender_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'pomodoro_session',
        sa.Column('work_duration', sa.Integer(), nullable=False),
        sa.Column('short_break_duration', sa.Integer(), nullable=False),
        sa.Column('long_break_duration', sa.Integer(), nullable=False),
        sa.Column('cycles_before_long', sa.Integer(), nullable=False),
        sa.Column('current_phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('completed_cycles', sa.Integer(), nullable=False),
        sa.Column('is_running', sa.Boolean(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.Uuid(), nullable=False),
        sa.Column('phase_ends_at', sa.DateTime(), nullable=True),
        sa.Column('session_ends_at', sa.DateTime(), nullable=True),
        sa.Column('last_updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['room_id'],
            ['room.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'room_participant',
        sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_kicked', sa.Boolean(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('room_id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('joined_at', sa.DateTime(), nullable=True),
        sa.Column('left_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['room_id'],
            ['room.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'board_element_comment',
        sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('board_element_id', sa.Integer(), nullable=False),
        sa.Column('author_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['board_element_id'],
            ['board_element.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_table('boardelementcomment')
    op.drop_table('pomodorosession')
    op.drop_table('roomparticipant')
    op.drop_table('projecttag')
    op.drop_table('chatmessage')
    op.drop_table('boardelement')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'boardelement',
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('element_type', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'], ['user.id'], name=op.f('boardelement_author_id_fkey')
        ),
        sa.ForeignKeyConstraint(
            ['room_id'], ['room.id'], name=op.f('boardelement_room_id_fkey')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('boardelement_pkey')),
    )
    op.create_table(
        'chatmessage',
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('is_edited', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['room_id'], ['room.id'], name=op.f('chatmessage_room_id_fkey')
        ),
        sa.ForeignKeyConstraint(
            ['sender_id'], ['user.id'], name=op.f('chatmessage_sender_id_fkey')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('chatmessage_pkey')),
    )
    op.create_table(
        'projecttag',
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['project_id'], ['project.id'], name=op.f('projecttag_project_id_fkey')
        ),
        sa.ForeignKeyConstraint(
            ['tag_id'], ['tag.id'], name=op.f('projecttag_tag_id_fkey')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('projecttag_pkey')),
    )
    op.create_table(
        'roomparticipant',
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('is_kicked', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            'left_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['room_id'], ['room.id'], name=op.f('roomparticipant_room_id_fkey')
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name=op.f('roomparticipant_user_id_fkey')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('roomparticipant_pkey')),
    )
    op.create_table(
        'pomodorosession',
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('work_duration', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            'short_break_duration', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            'long_break_duration', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            'cycles_before_long', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column('current_phase', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'completed_cycles', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column('is_running', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'phase_ends_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            'session_ends_at',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'last_updated_at',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ['room_id'], ['room.id'], name=op.f('pomodorosession_room_id_fkey')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pomodorosession_pkey')),
    )
    op.create_table(
        'boardelementcomment',
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            'board_element_id', sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['author_id'], ['user.id'], name=op.f('boardelementcomment_author_id_fkey')
        ),
        sa.ForeignKeyConstraint(
            ['board_element_id'],
            ['boardelement.id'],
            name=op.f('boardelementcomment_board_element_id_fkey'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('boardelementcomment_pkey')),
    )
    op.drop_table('board_element_comment')
    op.drop_table('room_participant')
    op.drop_table('pomodoro_session')
    op.drop_table('chat_message')
    op.drop_table('board_element')
    op.drop_table('project_tag')
    # ### end Alembic commands ###
