"""init

Revision ID: f8c83c8104aa
Revises: 23f51a1728a5
Create Date: 2026-03-17 17:14:00.349316

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'f8c83c8104aa'
down_revision: Union[str, Sequence[str], None] = '23f51a1728a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
