"""init

Revision ID: fc0bae9e1153
Revises: cf12f7faa765
Create Date: 2026-03-17 17:58:40.791173

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'fc0bae9e1153'
down_revision: Union[str, Sequence[str], None] = 'cf12f7faa765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
