PERMISSION_DESCRIPTIONS: dict[str, str] = {
    'profile:read': 'Read own profile',
    'profile:write': 'Update own profile',
    'users:read': 'Read other users data',
    'users:write': 'Create and update other users',
    'users:delete': 'Delete other users',
    'projects:read': 'Read projects',
    'projects:write': 'Create and update projects',
    'projects:delete': 'Delete projects',
    'tags:read': 'Read tags',
    'tags:write': 'Create and update tags',
    'tags:delete': 'Delete tags',
    'rooms:read': 'Read rooms',
    'rooms:write': 'Create and update rooms',
    'rooms:delete': 'Delete rooms',
    'participants:read': 'Read room participants',
    'participants:write': 'Update room participants',
    'participants:delete': 'Remove room participants',
    'chat:read': 'Read chat messages',
    'chat:write': 'Create and update chat messages',
    'chat:delete': 'Delete chat messages',
    'board:read': 'Read board elements and comments',
    'board:write': 'Create and update board elements and comments',
    'board:delete': 'Delete board elements and comments',
    'pomodoro:read': 'Read pomodoro state',
    'pomodoro:write': 'Create and update pomodoro state',
    'pomodoro:delete': 'Delete pomodoro state',
}

INITIAL_ROLE_SCOPES: dict[str, list[str]] = {
    'public': [
        'profile:read',
        'profile:write',
        'users:read',
        'projects:read',
        'tags:read',
        'rooms:read',
        'participants:read',
        'chat:read',
        'board:read',
        'pomodoro:read',
    ],
}