name: Init VM
on:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: GroupSessionsPlatform-KFU-2026/backend/.github/actions/ansible-setup@ci-cd-branch
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_B64 }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          vm_host: ${{ secrets.VM_HOST }}

      - name: Setup VM
        run: |
          cd ansible
          ansible-playbook \
            -i inventory.ini \
            -u ${{ secrets.VM_USER }} \
            --private-key ~/.ssh/host-group-session-platform \
            playbooks/init-vm-playbook.yaml
        env:
          ANSIBLE_FORCE_COLOR: "true"
          ANSIBLE_HOST_KEY_CHECKING: "false"